version: 2
registries:
  hydra-artifactory:
    type: maven-repository
    url: ${{ secrets.adaptive_uri }}
    username: ${{ secrets.adaptive_username }}
    password: ${{ secrets.adaptive_password }}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:05"
      timezone: "America/New_York"
    allow:
    - dependency-name: "com.weareadaptive*"
    groups:
      hydra:
        patterns:
        - "com.weareadaptive*"
    registries:
    - "hydra-artifactory"

