version: 2
registries:
  hydra-artifactory:
    type: maven-repository
    url: https://weareadaptive.jfrog.io/artifactory/hydra-release/
    username: ${{secrets.USERNAME}}
    password: ${{secrets.PASSWORD}}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:24"
      timezone: "America/New_York"
    allow:
    - dependency-name: "com.weareadaptive*"
    groups:
      hydra:
        patterns:
        - "com.weareadaptive*"
    registries:
    - "hydra-artifactory"

