version: 2
registries:
  hydra-artifactory:
    type: maven-repository
    url: https://1234567890.dkr.ecr.us-east-1.amazonaws.com
    username: ${{secrets.adaptive_username}}
    password: ${{secrets.adaptive_password}}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:10"
      timezone: "America/New_York"
    allow:
    - dependency-name: "com.weareadaptive*"
    groups:
      hydra:
        patterns:
        - "com.weareadaptive*"
    registries:
    - "hydra-artifactory"

