services:
  test:
    shm_size: '1gb'
    image: 'local/test'
    hostname: node0-driver
    ipc: "shareable"
    environment:
    networks:
      aeron:
        ipv4_address: 172.30.3.1

networks:
  aeron:
    driver: bridge
    name: 'aeron'
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.driver.mtu: 9000
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: 172.30.3.0/24
