name: Local Docker

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Docker context
        run: |
          systemctl is-active docker.service
          docker context ls
          docker ps -a