name: Local Docker

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Docker context
        run: |
          systemctl is-active docker.service
          docker context ls
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker build
        run: docker build -f docker/Dockerfile docker