name: Local Docker

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Docker context
        run: |
          systemctl is-active docker.service
          docker context ls
      - uses: actions/checkout@v4
      - name: Docker build
        run: docker build -f docker/Dockerfile docker -t local/test