name: quote fun

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
      - name: Set color
        id: color-selector
        run: >
          echo 
          '${{ format('{{Hello {0} {1} {2}!}}', 'Mona', 'the', 'Octocat') }}'
          
