name: quote fun

on:
  workflow_dispatch:

env:
  test: abc

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
      - name: Set color
        id: color-selector
        run: >
          curl -fsSL --max-time 30
            --url google.com/register
          
